// Microsoft. 2022. ASP.NET MVC Controller Overview (C#), 11 July 2022. [Online]. Available at: https://learn.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/controllers-and-routing/aspnet-mvc-controllers-overview-cs [Accessed 20 November 2025].
// Microsoft. 2022. Understanding Models, Views, and Controllers (C#), 11 July 2022. [Online]. Available at: https://learn.microsoft.com/en-us/aspnet/mvc/overview/older-versions-1/overview/understanding-models-views-and-controllers-cs [Accessed 20 November 2025].
// Microsoft. 2025. Part 6, controller methods and views in ASP.NET Core, 2 March 2025. [Online]. Available at: https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-9.0 [Accessed 20 November 2025]. 


using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using ST10085639_PROG6212_CMCS.Controllers;
using ST10085639_PROG6212_CMCS.Data;
using ST10085639_PROG6212_CMCS.Models;
using System.Globalization;
using System.Linq;


namespace ST10085639_PROG6212_CMCS.Controllers
{
    public class HRController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HRController(ApplicationDbContext db)
        {
            _db = db;
        }

        private bool IsHR()
        {
            var role = HttpContext.Session.GetString("Role");
            return role == "HR";
        }

        
        // HR DASHBOARD 
        public IActionResult HRView()
        {
            if (!IsHR())
                return RedirectToAction("Login", "Authentication");

            // Get all claims for the HR dashboard
            var claims = _db.Claims.ToList();

            // Return the view located at Views/HR/Index.cshtml
            return View("HRView",claims);
        }

        
        // INVOICE VIEW
        public IActionResult Invoice(int id)
        {
            if (!IsHR())
                return RedirectToAction("Login", "Authentication");

            var claim = _db.Claims.FirstOrDefault(c => c.ClaimID == id);
            if (claim == null)
                return NotFound();

            return View(claim); // Loads Invoice.cshtml
        }

        
        // DOWNLOAD INVOICE PDF
        public IActionResult DownloadInvoice(int id)
        {
            if (!IsHR())
                return RedirectToAction("Login", "Authentication");

            var claim = _db.Claims.FirstOrDefault(c => c.ClaimID == id);
            if (claim == null)
                return NotFound();

            using (var ms = new MemoryStream())
            {
                var document = new Document();
                PdfWriter.GetInstance(document, ms);
                document.Open();

                // Title
                var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 20);
                document.Add(new Paragraph("Claim Invoice", titleFont));
                document.Add(new Paragraph(" "));

                // Invoice header
                var headerFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 14);
                document.Add(new Paragraph($"Invoice for Claim ID: {claim.ClaimID}", headerFont));
                document.Add(new Paragraph(" "));

                // Claim details table
                PdfPTable table = new PdfPTable(2) { WidthPercentage = 100 };

                void AddRow(string label, string value)
                {
                    table.AddCell(new PdfPCell(new Phrase(label)) { BackgroundColor = BaseColor.LightGray });
                    table.AddCell(new Phrase(value));
                }

                AddRow("Lecturer Name:", claim.LecturerName);
                AddRow("Hours Worked:", claim.HoursWorked.ToString());
                AddRow("Hourly Rate:", claim.HourlyRate.ToString("C", CultureInfo.CreateSpecificCulture("en-ZA")));
                AddRow("Total Amount:", claim.TotalAmount.ToString("C", CultureInfo.CreateSpecificCulture("en-ZA")));
                AddRow("Status:", claim.Status);
                AddRow("Date Submitted:", claim.SubmittedDate.ToShortDateString());

                document.Add(table);

                // Footer
                document.Add(new Paragraph("\nGenerated by CMCS System"));
                document.Add(new Paragraph("Thank you."));

                document.Close();

                return File(ms.ToArray(), "application/pdf", $"Invoice_{claim.ClaimID}.pdf");
            }
        }
    }
}
